### ISSUE TITLE
✨ 是否可以添加一个定时下载关注列表的视频呢

### ISSUE THREAD

**Issue by GuoliangLai** [yutto-dev/yutto#102]
### 特性描述

目前我希望把脚本部署到服务器并用ql或crontab定时执行爬取获取视频号然后执行下载命令，这样搞感觉集成度不够。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 目前我希望把脚本部署到服务器并用ql或crontab定时执行爬取获取视频号然后执行下载命令，这样搞感觉集成度不够。

问题是什么呢？有点没搞懂，如果它们本身支持定时任务的话，那定时调用 yutto 就好了啊
