### ISSUE TITLE
✨ 能否添加一个只生成媒体元数据文件等功能

### ISSUE THREAD

**Issue by YanChenBai** [yutto-dev/yutto#104]
### 特性描述

当有些视频下载时忘记添加--with-metadata参数这样的话需要重新下载视频才能获得元数据文件

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
#105 将会提供这项功能，同时包含 `--metadata-only`、`--danmaku-only`、`--subtitle-only` 三个新选项，预计这两天就会 merge 并发布一个新版本～
