### ISSUE TITLE
✨购买的课程视频会支持吗

### ISSUE THREAD

**Issue by JeasonKim** [yutto-dev/yutto#119]
### 特性描述

购买的课程目前不支持下载，不知道后续有没有计划

### 建议解决方案

如果接受pull requests我可以开发一下后续推上来哈哈

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 购买的课程目前不支持下载，不知道后续有没有计划

目前暂无时间和精力去扩展这样的功能

> 如果接受pull requests我可以开发一下后续推上来哈哈

如果对整体运行逻辑改动不大的话是可以考虑的（比如可以复用当前的解析器逻辑）
