### ISSUE TITLE
🐛 使用 yutto 下载时，下载可能会突然停止或下载速度变为负数

### ISSUE THREAD

**Issue by OperatorRosmontis** [yutto-dev/yutto#124]
### 问题简述

使用 yutto 下载时，可能会出现下载突然停止，必须重新执行下载指令 或 下载速度变为负数，但稍等一会就能恢复正常 (这个"一会"可能只有5s，也可能长达5min) 的情况

### 复现方式

yutto (-b) --no-danmaku -c "**********" XXXXXX
* ********为SESSDAT，XXXXXX为视频/番剧/电影等的编号或链接
* () 表示可选，不影响复现

### 环境信息

-  OS: Windows 11 专业版 Insider Preview 22H2 25217.1010
-  Python: Python 3.11.3
-  yutto: yutto 2.0.0-beta.22
-  FFmpeg: ffmpeg version N-108625-g28ac2279ad-20221012
- 执行环境: Windows Terminal.Powershell
- 使用的用户权限: Administrator

### 额外信息

可能与程序版本无关

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by OperatorRosmontis** [comment]
下载突然停止，必须重新执行下载指令情况：
![Snipaste_2023-04-15_17-57-15](https://user-images.githubusercontent.com/61570274/232207049-099eb8f7-48d6-4ac7-b3db-f1c2f9aca068.png)
下载速度变为负数情况：
![Snipaste_2023-04-15_18-00-40](https://user-images.githubusercontent.com/61570274/232207187-026314b5-0ebd-42b1-a77e-cc8d4abf1399.png)

**Comment by OperatorRosmontis** [comment]
> ### 问题简述
> 使用 yutto 下载时，可能会出现下载突然停止，必须重新执行下载指令 或 下载速度变为负数，但稍等一会(可能长达50min，也可能短达5s)的情况
> 
> ### 复现方式
> yutto -b --no-danmaku -c "**********" XXXXXX
> 
> * : **********为SESSDAT，XXXXXX为视频/番剧/电影等的编号或链接
> 
> ### 环境信息
> * OS: Windows 11 专业版 Insider Preview 22H2 25217.1010
> * Python: Python 3.11.2
> * yutto: yutto 2.0.0-beta.20
> * FFmpeg: ffmpeg version N-108625-g28ac2279ad-20221012
> * Others: - 执行环境: Windows Terminal.Powershell
>   - 使用的用户权限: Administrator
> 
> ### 额外信息
> 可能与程序版本无关
> 
> ### 一点点的自我检查
> * [x]  充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
> * [x]  如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
> * [x]  本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
可以稍微调低 `--block-size` 试试，看样子是某个块迟迟没有下载完导致的

**Comment by OperatorRosmontis** [comment]
> 可以稍微调低 `--block-size` 试试，看样子是某个块迟迟没有下载完导致的

谢谢，请给出一个使用该参数的示例，我并未使用过该参数

**Comment by SigureMo** [comment]
> 谢谢，请给出一个使用该参数的示例，我并未使用过该参数

> 下载块大小
> - 参数 `-bs` 或 `--block-size`
> - 默认值 `0.5`
>
> 以 MiB 为单位，为分块下载时各块大小，不建议更改。

**Comment by OperatorRosmontis** [comment]
> > 谢谢，请给出一个使用该参数的示例，我并未使用过该参数
> 
> > 下载块大小
> > 
> > * 参数 `-bs` 或 `--block-size`
> > * 默认值 `0.5`
> > 
> > 以 MiB 为单位，为分块下载时各块大小，不建议更改。

类似于yutto -b -c "*******" -bs 0.3 XXXXX？

**Comment by OperatorRosmontis** [comment]
> 可以稍微调低 `--block-size` 试试，看样子是某个块迟迟没有下载完导致的

经过测试，并不是这个问题，调整了blockSize后对于bug的出现没有影响
