### ISSUE TITLE
🐛 群晖下载指定收藏夹大部分情况失败报错json.decoder.JSONDecodeError: Extra data

### ISSUE THREAD

**Issue by hbbbbbbbx** [yutto-dev/yutto#127]
### 问题简述

在群晖nas上定时任务运行(每小时运行一次)，下载指定收藏夹，相同的命令大部分情况下是失败，偶尔会成功，求解

报错如下：
> Traceback (most recent call last):
>   File "/usr/bin/yutto", line 8, in &lt;module&gt;
>     sys.exit(main())
>   File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 54, in main
> 
> 
> [94m INFO [0m 未提供 SESSDATA，无法下载会员专享剧集哟～
> 
> 
> ( ´･ω･) 
> 
>         
> (　´･ω) 
> 
>         
> ( 　´･) 
> 
>         
> ( 　 ´) 
>     run(args_list)
>   File "/usr/lib/python3.10/site-packages/yutto/utils/funcutils/as_sync.py", line 34, in sync_func
>     return asyncio.run(async_func(*args, **kwargs))
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 239, in run
>     download_list = await extractor(session, args)
>   File "/usr/lib/python3.10/site-packages/yutto/extractor/_abc.py", line 49, in __call__
>     return await self.extract(session, args)
>   File "/usr/lib/python3.10/site-packages/yutto/extractor/favourites.py", line 40, in extract
>     username, favourite_info = await asyncio.gather(
>   File "/usr/lib/python3.10/site-packages/yutto/api/space.py", line 36, in get_user_name
>     user_info = await Fetcher.fetch_json(session, space_info_url)
>   File "/usr/lib/python3.10/site-packages/yutto/utils/fetcher.py", line 35, in connect_n_times
>     return await connect_once(*args, **kwargs)
>   File "/usr/lib/python3.10/site-packages/yutto/utils/fetcher.py", line 113, in fetch_json
>     return await resp.json()
>   File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1120, in json
>     return loads(stripped.decode(encoding))
>   File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
>     raise JSONDecodeError("Extra data", s, end)
> json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)

### 复现方式

命令如下：
`docker run --rm -i -v /volume1/docker/yutto/download:/app siguremo/yutto "https://space.bilibili.com/xxxxxxxxx/favlist?fid=xxxxxx&ftype=create" -b`

大部分情况是失败的，偶尔成功，未发现规律。

### 环境信息

-  OS: DSM 7.1-42661
-  使用docker 2.0.0-beta.23

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
我试了下，看样子是 B 站的个人空间 API 挂掉了，我有空的时候看看能不能修一下吧，先使用收藏夹等功能代替吧

**Comment by hbbbbbbbx** [comment]
我指定了siguremo/yutto:2.0.0-beta.24，还是会报错，如下。
并且这个版本-v 显示的2.0.0-beta.23，是不是打包有问题呀

```
[94m INFO [0m 未提供 SESSDATA，无法下载会员专享剧集哟～


( ´･ω･) 

        
(　´･ω) 

        
( 　´･) 

        
( 　 ´) 
    sys.exit(main())
  File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 54, in main
    run(args_list)
  File "/usr/lib/python3.10/site-packages/yutto/utils/funcutils/as_sync.py", line 34, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/site-packages/yutto/__main__.py", line 239, in run
    download_list = await extractor(session, args)
  File "/usr/lib/python3.10/site-packages/yutto/extractor/_abc.py", line 49, in __call__
    return await self.extract(session, args)
  File "/usr/lib/python3.10/site-packages/yutto/extractor/favourites.py", line 40, in extract
    username, favourite_info = await asyncio.gather(
  File "/usr/lib/python3.10/site-packages/yutto/api/space.py", line 36, in get_user_name
    user_info = await Fetcher.fetch_json(session, space_info_url)
  File "/usr/lib/python3.10/site-packages/yutto/utils/fetcher.py", line 35, in connect_n_times
    return await connect_once(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/yutto/utils/fetcher.py", line 113, in fetch_json
    return await resp.json()
  File "/usr/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1120, in json
    return loads(stripped.decode(encoding))
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 47 (char 46)
```

**Comment by hbbbbbbbx** [comment]
> > 并且这个版本-v 显示的2.0.0-beta.23，是不是打包有问题呀
> 
> 我这边 docker 镜像使用清华源构建的，应该是构建的时候清华源还没有同步最新版，已经重新 build 了一版，麻烦测试一下～

刚才试了，没问题了，感谢大佬
