### ISSUE TITLE
🐛 访问权限不足

### ISSUE THREAD

**Issue by kFoodie** [yutto-dev/yutto#138]
### 问题简述

yutto/api/space.py", line 38, in get_user_name
    return user_info["data"]["name"]
KeyError: 'data'
```
{'code': -403, 'message': '访问权限不足', 'ttl': 1}
```

请问这是代理的问题吗？

### 复现方式

 yutto https://space.bilibili.com/100969474/video -d videos/bili_0518 

### 环境信息

-  OS:  ubuntu
-  Python:  3.9
-  yutto:  2.0.0-beta.25
-  FFmpeg:  version 5.1.2

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
看样子是 B 站 API 变了，有些参数是必需的了，等我有时间的时候看看吧

**Comment by kFoodie** [comment]
> 看样子是 B 站 API 变了，有些参数是必需的了，等我有时间的时候看看吧

感谢回复。

**Comment by FrankHB** [comment]
不用代理，这两天一直下载不了，目测就是 B 站 API 变了。

（不只是这里直播间挂机脚本也抽风……`SESSDATA` 好像首页上也可能取不到。）

**Comment by SigureMo** [comment]
现在看起来所有参数都需要才能正确访问：

<img width="447" alt="image" src="https://github.com/yutto-dev/yutto/assets/38436475/18ad968f-7f56-495e-8243-9487efc3a812">

这里关键是 `web_location` 和 `w_rid` 的获取方式，`wts` 一看就知道是当前时间，这个好说

搜 `w_rid` 的 value 发现基本搜不到，看样子不是 server 端返回的，应该是 client 端计算得到的，直接搜 `w_rid` 可以发现两段相关 JS 代码，这里所用的应该是二者之一：

```js
     function encWbi(e, t) {
        t || (t = {});
        var r = getWbiKey(t)
          , n = r.imgKey
          , i = r.subKey;
        if (n && i) {
            for (var o = getMixinKey(n + i), a = Math.round(Date.now() / 1e3), s = Object.assign({}, e, {
                wts: a
            }), l = Object.keys(s).sort(), c = [], u = /[!'\(\)*]/g, d = 0; d < l.length; d++) {
                var h = l[d]
                  , p = s[h];
                p && "string" == typeof p && (p = p.replace(u, "")),
                null != p && c.push("".concat(encodeURIComponent(h), "=").concat(encodeURIComponent(p)))
            }
            var f = c.join("&");
            return {
                w_rid: md5(f + o),
                wts: a.toString()
            }
        }
        return null
    }
```

```js
         if (i && a) {
            for (var c = (n = i + a,
            r = [],
            [46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5, 49, 33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13, 37, 48, 7, 16, 24, 55, 40, 61, 26, 17, 0, 1, 60, 51, 30, 4, 22, 25, 54, 21, 56, 59, 6, 63, 57, 62, 11, 36, 20, 34, 44, 52].forEach((function(t) {
                n.charAt(t) && r.push(n.charAt(t))
            }
            )),
            r.join("").slice(0, 32)), s = Math.round(Date.now() / 1e3), p = Object.assign({}, t, {
                wts: s
            }), d = Object.keys(p).sort(), h = [], v = /[!'\(\)*]/g, m = 0; m < d.length; m++) {
                var y = d[m]
                  , g = p[y];
                g && "string" == typeof g && (g = g.replace(v, "")),
                null != g && h.push("".concat(encodeURIComponent(y), "=").concat(encodeURIComponent(g)))
            }
            var b = h.join("&");
            return {
                w_rid: u(b + c),
                wts: s.toString()
            }
        }
```

估计还原下算法就可以了……

**Comment by lc4t** [comment]
> 现在看起来所有参数都需要才能正确访问：
> 
> <img alt="image" width="447" src="https://user-images.githubusercontent.com/38436475/240813004-18ad968f-7f56-495e-8243-9487efc3a812.png">
> 这里关键是 `web_location` 和 `w_rid` 的获取方式，`wts` 一看就知道是当前时间，这个好说
> 
> 搜 `w_rid` 的 value 发现基本搜不到，看样子不是 server 端返回的，应该是 client 端计算得到的，直接搜 `w_rid` 可以发现两段相关 JS 代码，这里所用的应该是二者之一：
> 
> ```js
>      function encWbi(e, t) {
>         t || (t = {});
>         var r = getWbiKey(t)
>           , n = r.imgKey
>           , i = r.subKey;
>         if (n && i) {
>             for (var o = getMixinKey(n + i), a = Math.round(Date.now() / 1e3), s = Object.assign({}, e, {
>                 wts: a
>             }), l = Object.keys(s).sort(), c = [], u = /[!'\(\)*]/g, d = 0; d < l.length; d++) {
>                 var h = l[d]
>                   , p = s[h];
>                 p && "string" == typeof p && (p = p.replace(u, "")),
>                 null != p && c.push("".concat(encodeURIComponent(h), "=").concat(encodeURIComponent(p)))
>             }
>             var f = c.join("&");
>             return {
>                 w_rid: md5(f + o),
>                 wts: a.toString()
>             }
>         }
>         return null
>     }
> ```
> 
> ```js
>          if (i && a) {
>             for (var c = (n = i + a,
>             r = [],
>             [46, 47, 18, 2, 53, 8, 23, 32, 15, 50, 10, 31, 58, 3, 45, 35, 27, 43, 5, 49, 33, 9, 42, 19, 29, 28, 14, 39, 12, 38, 41, 13, 37, 48, 7, 16, 24, 55, 40, 61, 26, 17, 0, 1, 60, 51, 30, 4, 22, 25, 54, 21, 56, 59, 6, 63, 57, 62, 11, 36, 20, 34, 44, 52].forEach((function(t) {
>                 n.charAt(t) && r.push(n.charAt(t))
>             }
>             )),
>             r.join("").slice(0, 32)), s = Math.round(Date.now() / 1e3), p = Object.assign({}, t, {
>                 wts: s
>             }), d = Object.keys(p).sort(), h = [], v = /[!'\(\)*]/g, m = 0; m < d.length; m++) {
>                 var y = d[m]
>                   , g = p[y];
>                 g && "string" == typeof g && (g = g.replace(v, "")),
>                 null != g && h.push("".concat(encodeURIComponent(y), "=").concat(encodeURIComponent(g)))
>             }
>             var b = h.join("&");
>             return {
>                 w_rid: u(b + c),
>                 wts: s.toString()
>             }
>         }
> ```
> 
> 估计还原下算法就可以了……

参考这个：https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md

**Comment by SigureMo** [comment]
> 参考这个：[SocialSisterYi/bilibili-API-collect@master/docs/misc/sign/wbi.md](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/misc/sign/wbi.md?rgh-link-date=2023-05-25T05%3A57%3A25Z)

嗯，这个项目我知道的，我也知道大概那边已经有了相关的算法，但这个看样子所有算法都写在 JS 里了，稍微花点时间就能找到加密方式……
