### ISSUE TITLE
🐛 Docker 最新版本 `siguremo/yutto:2.0.0-beta.26` 版本实际运行的是 `2.0.0-beta.25` 版本

### ISSUE THREAD

**Issue by DIYgod** [yutto-dev/yutto#144]
### 问题简述

Docker 最新版本 `siguremo/yutto:2.0.0-beta.26` 版本实际运行的是 `2.0.0-beta.25` 版本

影响是 space api 依然无法使用

### 复现方式

```sh
docker pull siguremo/yutto:2.0.0-beta.26
docker run --rm siguremo/yutto:2.0.0-beta.26 -v
```

输出 `yutto 2.0.0-beta.25`

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  yutto: yutto 版本号 (`yutto -v`)
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
已重新发布，现在应该没问题了，麻烦测试一下～

```
.venv ❯ docker pull siguremo/yutto:2.0.0-beta.26                                
2.0.0-beta.26: Pulling from siguremo/yutto
08409d417260: Already exists 
add82bc5a581: Pull complete 
a08984ed2ea8: Pull complete 
Digest: sha256:a1aa3cab15b09c2eeff9556fd8eb4f8f36cb55692666e0a70d123e75b519bdb5
Status: Downloaded newer image for siguremo/yutto:2.0.0-beta.26
docker.io/siguremo/yutto:2.0.0-beta.26

.venv ❯ docker run --rm siguremo/yutto:2.0.0-beta.26 -v                             
yutto 2.0.0-beta.26
```

因为 Docker 里用的 PyPI 清华镜像，不知道为啥最近一直不靠谱，这都发布两周了都没有同步最新的 2.0.0-beta.26，我得找时间改下 Dockerfile 配置了 ( ๑ˊ•̥▵•)੭₎₎

**Comment by DIYgod** [comment]
现在没问题了，非常感谢~
