### ISSUE TITLE
✨ 标题判断

### ISSUE THREAD

**Issue by kFoodie** [yutto-dev/yutto#153]
### 特性描述

下载的视频，有没有办法判断标题的文字？比如，如果视频的标题包含日文的，我不想下载

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 比如，如果视频的标题包含日文的，我不想下载

这需求也太定制化了吧……难道在 cli 里传一个函数判断是否有日语假名？你有什么 user friendly 接口推荐的话，才可以考虑实现在 yutto 内，否则只能自行通过额外的脚本实现

**Comment by kFoodie** [comment]
比如我在获取某个up主的所有投稿视频之前，能否返回他下面所有视频的title啊？
https://space.bilibili.com/1/video
yutto是有获取视频标题这个功能的吧，希望能把这个功能单独暴露出来。方便我加判断哩

**Comment by SigureMo** [comment]
> yutto是有获取视频标题这个功能的吧，希望能把这个功能单独暴露出来。方便我加判断哩

yutto 无暴露 API 的打算，只有 cli，如果有需要，只能自行查看源码
