### ISSUE TITLE
🐛 401 非法访问

### ISSUE THREAD

**Issue by kFoodie** [yutto-dev/yutto#156]
### 问题简述

命令：
```
yutto https://space.bilibili.com/100969474/video --output-format-audio-only mp4 -d videos/bili_0705_5 --audio-only --no-danmaku -b  -aq 30216 -n 64
```
错误1： yutto/api/space.py 34行

> json_data:  {'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '29facb8364042fd55afa1312c664a78e', 'decision_ctx': {'buvid': '', 'decision_type': '4', 'ip': '39.101.64.125', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'v_checkIds': '', 'v_seconds': '120', 'v_times': '100', 'v_voucher': 'voucher_fef79873-7f0a-4d4e-8f0f-71c7871cfaec'}}}}

错误2： yutto/api/space.py 46行

> user_info:  {'code': -401, 'message': '非法访问', 'ttl': 1, 'data': {'ga_data': {'decisions': ['verify_captcha_level2'], 'risk_level': 1, 'grisk_id': '2fc5f5b689743a7a4f6825229064a78e', 'decision_ctx': {'buvid': '', 'decision_type': '4', 'ip': '39.101.64.125', 'mid': '0', 'origin_scene': 'anti_crawler', 'scene': 'anti_crawler', 'ua': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36', 'v_checkIds': '', 'v_seconds': '120', 'v_times': '100', 'v_voucher': 'voucher_70f99d56-7633-4a3b-9e5d-296e0ce06121'}}}}

### 复现方式

```
yutto https://space.bilibili.com/100969474/video --output-format-audio-only mp4 -d videos/bili_0705_5 --audio-only --no-danmaku -b  -aq 30216 -n 64
```

### 环境信息

-  OS: 操作系统类型及其版本号 ubuntu 20
-  Python: Python 版本号 (`python --version`) 3.9
-  yutto: yutto 版本号 (`yutto -v`) yutto 2.0.0-beta.26

### 额外信息

偶发情况，请问是ip被封了吗？

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> anti_crawler

明显是被封了

**Comment by kFoodie** [comment]
求助，有啥解决方法不？可能是爬太快被封了？

**Comment by kFoodie** [comment]
用IP代理池在__main__.py给fetch调协了proxy也不行。。救命。。

**Comment by kFoodie** [comment]
IP解封了。为啥设置了代码反而下载不了，不设置代理反而可以？
代理IP：101.37.161.171:80
