### ISSUE TITLE
✨ 对于番剧链接直接跳转到 `-b` 批量下载模式而不是报错

### ISSUE THREAD

**Issue by z0z0r4** [yutto-dev/yutto#168]
### 特性描述

```
PS C:\Users\DELL> yutto https://www.bilibili.com/bangumi/media/md2572
 INFO  未提供 SESSDATA，无法下载会员专享剧集哟～
 ERROR  url 不正确，也许该 url 仅支持批量下载，如果是这样，请使用参数 -b～
 INFO  已终止下载，再次运行即可继续下载～
```
显得很多余，有的链接喂进来注定就是批量下载的...

### 建议解决方案

识别可批量下载的，自动处理

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
这个设计当前是不会变的，无 `-b` 永远只会下载一个视频，`yutto` 只会承担这一种语义，而 `yutto -b` 才会承担批量下载的语义

这样用户永远知道自己在做什么（下载一个还是多个视频），而不是将控制权交给程序

**Comment by z0z0r4** [comment]
但 [md2572](https://www.bilibili.com/bangumi/media/md2572) 不是显然只能下载多个视频吗？
