### ISSUE TITLE
sessdata 失效时返回错误✨ 

### ISSUE THREAD

**Issue by aheadlead** [yutto-dev/yutto#176]
### 特性描述

现在版本在 sessdata 失效时，会自动回退到未登录状态。自动化脚本无法感知到 sessdata 失效，导致预期下载高画质，实际下载 480p 低画质版本。

### 建议解决方案

提供一个 --strict-sessdata 的 flag，当启用这个 flag 且 sessdata 无效时，yutto 直接退出，并返回非零返回值。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by lc4t** [comment]
根据README, 使用
```
严格校验大会员状态有效
参数 --vip-strict
默认值 False
```
试试

**Comment by aheadlead** [comment]
> 根据README, 使用
> 
> ```
> 严格校验大会员状态有效
> 参数 --vip-strict
> 默认值 False
> ```
> 
> 试试

谢谢你的快速回复，我在发 issue 前有测试过这个开关。

因为我测试用的 b 站账号没有开大会员，所以不论我的 sessdata 是否有效，这个 --vip-strict 都会让程序直接退出。

这个和我预期有一点不一样～

**Comment by lc4t** [comment]
> 

哦明白了，你其实想要的是登录态的校验而非大会员的校验...
目前确实没有非大会员账号的登录态校验选项..

**Comment by lc4t** [comment]
#179
