### ISSUE TITLE
🐛 文件名太长，报错

### ISSUE THREAD

**Issue by MyLeoLan** [yutto-dev/yutto#196]
### 问题简述

可能是由于文件系统(ext4)或特殊字符的问题。可否提供指定别名、缩短名称等选项。
<img width="1241" alt="image" src="https://github.com/yutto-dev/yutto/assets/18298528/74bcef92-f63f-4571-90ab-a989205250e7">

### 复现方式

链接：https://www.bilibili.com/video/BV1nA4y1X7ux

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
Python 3.11.6

-  yutto: yutto 版本号 (`yutto -v`)
yutto 2.0.0-beta.31

-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
ffmpeg 6.0

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 可否提供指定别名、缩短名称等选项。

子路径模板即可实现
https://github.com/yutto-dev/yutto?tab=readme-ov-file#%E5%AD%98%E6%94%BE%E5%AD%90%E8%B7%AF%E5%BE%84%E6%A8%A1%E6%9D%BF
