### ISSUE TITLE
🐛下载类似 https://space.bilibili.com/361469957/channel/collectiondetail?sid=23195格式的视频集合时 使用模板{id}这个id始终为1

### ISSUE THREAD

**Issue by NightMoonIsland** [yutto-dev/yutto#197]
### 问题简述

🐛 https://space.bilibili.com/361469957/channel/collectiondetail?sid=23195格式下使用模板{id}这个id始终为1

### 复现方式

下载 格式类似 https://space.bilibili.com/361469957/channel/collectiondetail?sid=23195 使用模板重命名 -tp {id}后这个id始终是1

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 Python 3.10.10
-  yutto: yutto 版本号 yutto 2.0.0-beta.30
-  FFmpeg: FFmpeg 版本号 ffmpeg version 2023-11-05-git-44a0148fad-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 
> |Variable|Description|Scope|
> |-|-|-|
> |...|...|...|
> |id|系列视频单 p 顺序标号|全部|
> |...|...|...|

「系列视频单 p 顺序标号」，只有 1P，id 自然是 1
