### ISSUE TITLE
✨ 希望可以增加从json读取链接批量创建多up全部投稿下载任务的功能

### ISSUE THREAD

**Issue by vanichocola** [yutto-dev/yutto#207]
### 特性描述

ː̗̀(o›ᴗ‹o)ː̖́

### 建议解决方案

ː̗̀(o›ᴗ‹o)ː̖́

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
https://github.com/yutto-dev/yutto#%E4%BD%BF%E7%94%A8%E4%BB%BB%E5%8A%A1%E5%88%97%E8%A1%A8

为什么要使用 JSON 呢？任务列表解决不了么？

**Comment by SigureMo** [comment]
无回复，默认上面的解决方案是可以的，先 close，如有疑问可以 reopen
