### ISSUE TITLE
🐛 网络频繁报错该怎么处理？

### ISSUE THREAD

**Issue by sonderscode** [yutto-dev/yutto#208]
### 问题简述

<img width="507" alt="image" src="https://github.com/yutto-dev/yutto/assets/23073985/a012ab36-b366-4f12-a4f3-49fb1d7c3a63">

在vps上下载主播录播（也就是合集任务），目前下载了400个g左右了，每个视频都如图片里那样疯狂报错，只能一卡一卡的啃完，偶尔进程被kill掉，要重新执行下载任务，然后网络报错依然会出现

<img width="687" alt="image" src="https://github.com/yutto-dev/yutto/assets/23073985/ab7f0cb8-59d3-4846-9dd3-3fbba4509d09">

是否和同一个大会员cookie有关？还是说因为在一个vps上，ip被锁定限流了？

### 复现方式

在该VPS上任意找一个链接添加到下载任务即可复现

### 环境信息

-  OS: ubuntu0.22.04.1 （美国地区vps）
-  Python: Python 3.10.12
-  yutto: yutto 2.0.0-beta.31
-  FFmpeg: ffmpeg version 4.4.2

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by dydhyhwu** [comment]
大概率是被限流了， 同一台vps上持续并发太高了。 你换一个vps试试

**Comment by sonderscode** [comment]
> 大概率是被限流了， 同一台vps上持续并发太高了。 你换一个vps试试

目前只有一个VPS，主要是需要空间来搬运，要买储存盘，就没多搞。

**Comment by SAENE** [comment]
同样的问题，下载免费观看的就很正常

**Comment by SigureMo** [comment]
> 目前下载了400个g左右了

这个 yutto 没办法，用啥都没办法，剩下的过会儿再下呗……

> 同样的问题，下载免费观看的就很正常

同样的现象还是同样的使用方式？

同样的短时间高并发那是同一个问题，yutto 没办法解决

如果只是同样的现象，而并非高并发，而且不是自身网络问题的话，请新开 issue 详述问题，目前的描述无帮助定位问题的有效信息
