### ISSUE TITLE
🐛 个别链接下载过程命令行无异常，文件夹都正常出现，维度缺少视频本体文件

### ISSUE THREAD

**Issue by vanichocola** [yutto-dev/yutto#209]
### 问题简述

如题，所有的一切都正常，只有本该出现的视频mp4文件不存在,目前仅在使用复现方式中的url会出现该情况，未在其他url出现过

### 复现方式

```bash
yutto https://space.bilibili.com/19350359/video -q 127 --vcodec hevc:copy --output-format mp4 --no-danmaku --no-subtitle -b -c xxxxxxxx
```

### 环境信息

-  OS: windows11 23h2
-  Python: 3.11.6
-  yutto: yutto 2.0.0-beta.31
-  FFmpeg: ffmpeg version 2023-12-21-git-1e42a48e37-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: powershell
-  Others: 其它信息息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
cookie 信息帮你删掉了，注意隐私

**Comment by vanichocola** [comment]
> cookie 信息帮你删掉了，注意隐私

大意了，感谢

**Comment by SigureMo** [comment]
已于 #210 修复
