### ISSUE TITLE
✨ 支持注销用户的视频下载

### ISSUE THREAD

**Issue by yllhwa** [yutto-dev/yutto#222]
### 特性描述

测试用户：https://space.bilibili.com/360193236

注销后无法通过接口获取用户名称，但是投稿列表的接口是可以正常使用的。

### 建议解决方案

可以在获取用户名称的接口失败后尝试fallback到注销用户上，例如统一为`账号已注销 {mid}`

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
看起来可以，有兴趣实现一下么？或者我稍后实现一下也可以

**Comment by SigureMo** [comment]
> 可以在获取用户名称的接口失败后尝试fallback到注销用户上，例如统一为`账号已注销 {mid}`

这里有一个建议，最好不要失败就直接 fallback，如果能判断是因为注销而导致的失败的话，最好仅在该情况 fallback，否则依然报错，不然可能会有些意料之外的 bug

当然这里的前提是能知道这个用户是否已经注销
