### ISSUE TITLE
✨ 建议仅下载弹幕或字幕时无需大会员账号

### ISSUE THREAD

**Issue by fxb6666** [yutto-dev/yutto#235]
### 特性描述

据我所知，下载弹幕是不需要登录的。所以能不能改成仅下载会员番剧的弹幕时不再要求有大会员账号。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
已于 #236 支持～稍后发布新版本
