### ISSUE TITLE
✨ 关于想下载番剧指定剧集得到的却是预告视频这档事

### ISSUE THREAD

**Issue by fxb6666** [yutto-dev/yutto#237]
### 特性描述

一般情况下，我们想下载的是正片，但有时得到的却是预告。例如：`yutto -q 32 -aq 30232 --vcodec avc:copy -b -p 5 https://www.bilibili.com/bangumi/play/ep783826`得到的是第5集的预告，而且没有提示这是预告，只能根据文件体积来判断。

### 建议解决方案

可能的解决方案（任选其一）：
1. 把所有预告视频都排除，缺点是或许真有哪个小可爱想下载预告视频却发现不能下载而略感遗憾也不一定。
2. 新增一个参数`--preview`或使用现有的`-s`/`--with-section`参数，只有指定此参数时才包括预告视频。
3. 为预告视频添加提示，并像[bilili](https://github.com/yutto-dev/bilili)一样在下载前需要输入`y`确认。
4. 新增一个参数`--list`，指定此参数时仅列出每集的标题和编号而不会进行下载。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
感谢反馈这一新的 case～

yutto 其实是有针对这一情况的处理的，目前是报 warning：

<img width="789" alt="image" src="https://github.com/yutto-dev/yutto/assets/38436475/973aa1f6-8c6e-4105-b294-202dea096a7b">

但从返回数据上来看，这个视频并不是预告（`is_preview == 0`），但却只有 45s，也就是说事实上确实是预告，可能 B 站对预告又有什么新的标志了？我之后看一下返回数据里有什么地方可以标识这一点

**Comment by SigureMo** [comment]
暂时在 #239 加回了 warning，关于通过选项来跳过预告之后会考虑下

**Comment by fxb6666** [comment]
好吧，看来程序是按照视频编号来选择的，这样需要手动打开网页确认编号。再说个小问题，“ERROR”和“WARN”显示的`avid`实际输出的是bv号。
![Screenshot_20240218_091731](https://github.com/yutto-dev/yutto/assets/102399040/e457f73d-6e6f-44d8-b908-dfd2d60cbaaa)

**Comment by SigureMo** [comment]
> 再说个小问题，“ERROR”和“WARN”显示的avid看到第一眼以为是aid，实际输出的是bv号。

已在 #240 调整
