### ISSUE TITLE
✨ 增加批量下载频率限制/时间间隔参数/指定完整 cookie&UA

### ISSUE THREAD

**Issue by pecliu** [yutto-dev/yutto#242]
### 特性描述

用来批量下载剧集后，经常被检测异常然后被 B 站_**冻结大会员**_半个小时

### 建议解决方案

1. 增加下载频率限制的参数。比如下载完前一个后，delay n 分钟再下载下一个。
又或者每小时最多下载 n 个视频参数配置

2. 增加参数指定 config 文件。文件中可以指定全量 cookie、以及 UA

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 增加下载频率限制的参数。比如下载完前一个后，delay n 分钟再下载下一个。

已在 #244 支持

> 增加参数指定 config 文件。文件中可以指定全量 cookie、以及 UA

虽然从过去到现在有零星几个提到 config 的需求，但我始终没有发现 yutto 对此有什么强需求，yutto 简洁的命令行界面我认为已经足矣，全量 cookie 完全是一个冗余的参数，UA 更是没有必要指定

参数的添加绝对是一个值得深思熟虑的过程，并不是说有什么需求就要加什么，需要同时权衡能否出色地完成需求，而且还在兼顾可扩展性的情况下做到最简

类似全量 cookie、UA 的需求我不认为是需求，只是使用习惯罢了，如果不愿意使用当前用户界面，完全可以自己 fork 后修改源码使用
