### ISSUE TITLE
🐛 下载合集视频时封面获取错误

### ISSUE THREAD

**Issue by LockRim** [yutto-dev/yutto#246]
### 问题简述

下载分p视频时，除第一个视频为封面之外其余视频为开头前2帧的图片
不过早期的分p视频则没有该情况

![image](https://github.com/yutto-dev/yutto/assets/52944370/ff5b175d-d3a8-4c77-915b-7f7153741cf2)
![image](https://github.com/yutto-dev/yutto/assets/52944370/1e48cb48-1262-46dc-9cae-c01ff9d4edc7)

### 复现方式

错误样例
```
yutto -b https://www.bilibili.com/video/BV1pZ421z7GL/
```

成功样例
```
yutto -b https://www.bilibili.com/video/BV1Lo4y1d7zL/
```

### 环境信息

-  OS: archlinux 6.7.6-arch1-1
-  Python: Python 3.11.7
-  yutto: yutto 2.0.0-beta.36
-  FFmpeg: ffmpeg version n6.1.1 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 13.2.1 (GCC) 20230801

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by LockRim** [comment]
补充发现：
单独下载合集视频时也会出现该情况
```
yutto 'https://www.bilibili.com/video/BV1pZ421z7GL?p=15'
```

**Comment by SigureMo** [comment]
> 下载分p视频时，除第一个视频为封面之外其余视频为开头前2帧的图片

因为多 P 视频只有一个封面，非第一 P 只能使用 `first_frame`，也就是第一帧

> 单独下载合集视频时也会出现该情况

这不是「合集」，只是多 P 视频

或者你认为多 P 视频都应该使用同一「封面」么？那是否难以区分呢？这点我不是很确定

**Comment by LockRim** [comment]
那确实是我理解错了多p和合集的区别，抱歉

出于个人习惯我会使用 `{title}/{id} - {name}` 来保存多p视频，这样能确保下载的多p视频的顺序与原视频一致

至于区分，对于保存在一个文件夹下的多p视频来说，同一封面和不同封面区别并不大，更多的还是看标题，出于美观来说，同一封面的观感会更好

这样来看，我是请求一个新特性，或许应该改个issue的名字了（

**Comment by SigureMo** [comment]
已在 #247 统一使用封面
