### ISSUE TITLE
✨ 是否考虑添加章节信息

### ISSUE THREAD

**Issue by LockRim** [yutto-dev/yutto#248]
### 特性描述

B站的部分视频使用章节来划分不同的内容，来实现快速跳转
如：https://www.bilibili.com/video/BV1pV4y1R7p8/

添加章节信息可以方便本地查看时与网页一样实现快速跳转，大部分播放器也实现了章节跳转的功能

章节信息以元数据形式保存，不过与配置中的nfo不同

### 建议解决方案

ffmpeg添加章节信息的教程如下
https://wklchris.github.io/blog/FFmpeg/FFmpeg.html#id26

网页端找到保存章节信息的内容在 `bpx-player-ctrl-viewpoint-menu` 中，`bpx-player-ctrl-viewpoint-menu-item` 则包含了开始时间和标题
B站的章节以秒为单位，所以我们可以使用 `TIMEBASE=1/1` 规定为秒，最后一个章节的末尾可以设置为一无限大的值，可以不用获取视频总时长

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by zjns** [comment]
@SigureMo 看了下 这个接口 https://api.bilibili.com/x/player/v2?cid=1063247402&aid=866374002 可以拿到章节和字幕信息
