### ISSUE TITLE
✨ 支持处理杜比音轨

### ISSUE THREAD

**Issue by zjns** [yutto-dev/yutto#254]
### 特性描述

支持单独及合并下载杜比音轨

### 建议解决方案

无

### 额外信息

示例视频 [BV1yu4y1P7wm](https://www.bilibili.com/video/BV1yu4y1P7wm)。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [X] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
实现上应该没啥难度，只是设计上上的问题 #62
