### ISSUE TITLE
✨ 是否考虑将.aac文件，直接下载为mp3

### ISSUE THREAD

**Issue by lbl1120** [yutto-dev/yutto#264]
### 问题简述

是否考虑将.aac文件，直接下载为mp3

### 复现方式

是否考虑将.aac文件，直接下载为mp3

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  yutto: yutto 版本号 (`yutto -v`)
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 额外信息

是否考虑将.aac文件，直接下载为mp3

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [X] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
#265 允许了使用 `mp3` 作为输出格式，因此现在是可以办到的了

比如：

```bash
yutto BV1ur421x75Y --audio-only --acodec="mp4a:libmp3lame" --output-format-audio-only=mp3
```

注意既然 `--output-format-audio-only` 不使用默认的 `infer`，那么就不能保证在任何场景下这个命令是有效的，用户需要自己承担潜在的自定义输出格式以及自定义输出编码不匹配的问题

另外，是不会将默认格式改为 `mp3` 的，因为这需要额外编码

上次发版到这次发版没累积什么 feature，短期内不会发版，如有需求通过 pipx 装 main 分支版本体验吧

```bash
pipx install git+https://github.com/yutto-dev/yutto@main
```

以及这不是 bug，不要选择 https://github.com/yutto-dev/yutto/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml template
