### ISSUE TITLE
✨ 如果网络不稳定会频繁在控制台输出日志

### ISSUE THREAD

**Issue by violetnight** [yutto-dev/yutto#275]
### 特性描述

✨
网络不稳定时网络超时和下载出错尝试重连的信息频繁刷控制台

### 建议解决方案

希望能把警告这种错误写到文件里，不输出到控制台，或者控制重连的次数，也可以增加参数给用户自助屏蔽这种错误

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [X] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
> 网络不稳定时网络超时和下载出错尝试重连的信息频繁刷控制台

到底有多频繁呢？从来没遇到过频繁到影响阅读的问题

> 希望能把警告这种错误写到文件里，不输出到控制台

可以考虑将这部分输出到 stderr，自己手动重定向，yutto 不提供也没什么必要提供这类逻辑

或者 log level 分级，现在本来就是将 debug level 用 `--debug` 控制的，warning 本就是应该看到的内容，因为网络问题本来就是用户应该知道的事情，默认就应该输出

**Comment by violetnight** [comment]
> > 网络不稳定时网络超时和下载出错尝试重连的信息频繁刷控制台
> 
> 到底有多频繁呢？从来没遇到过频繁到影响阅读的问题
> 
> > 希望能把警告这种错误写到文件里，不输出到控制台
> 
> 可以考虑将这部分输出到 stderr，自己手动重定向，yutto 不提供也没什么必要提供这类逻辑
> 
> 或者 log level 分级，现在本来就是将 debug level 用 `--debug` 控制的，warning 本就是应该看到的内容，因为网络问题本来就是用户应该知道的事情，默认就应该输出

用的随身wifi，基本被这种警告shua刷屏了

![微信截图_20240605100227](https://github.com/yutto-dev/yutto/assets/17923639/70ce2358-f34a-4143-8a88-4288bce927b4)

**Comment by Aqua256** [comment]
事实上可以直接重定向到一个log文件
`yutto <url> > log`
