### ISSUE TITLE
🐛 分P名相同会导致下载失败

### ISSUE THREAD

**Issue by DYS763** [yutto-dev/yutto#280]
### 问题简述

 如果下载的视频分P名一致，会导致文件冲突进而下载失败。

### 复现方式

例如：
某视频有3个分P，分P名分别为：
1.abc
2.abc
3.def
下载合并的时候会因为p1和p2所保存的文件名一致导致出现错误

### 环境信息

-  OS: Windows
-  Python:3.12
-  bilili: 1.4.15
-  FFmpeg: 6.1.1

### 额外信息

建议：下载的文件名保留分P信息（例如把现在的abc.mp4改为1.abc.mp4）

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/bilili) 与[文档](https://bilili.nyakku.moe/)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 bilili 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/bilili/issues) 和 [discussion](https://github.com/yutto-dev/bilili/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
已在 yutto main 修复，可以使用以下命令来安装 main 分支最新版来验证

```bash
pipx install git+https://github.com/yutto-dev/yutto.git@main --force
```
