### ISSUE TITLE
✨ 增加弹幕过滤功能

### ISSUE THREAD

**Issue by Super-Passerby** [yutto-dev/yutto#291]
### 特性描述

1、使用中遇到的问题：目前无法自定义弹幕的相关参数，只能选择下载or不下载，一些热门的视频的弹幕叠在一起，比较影响观看体验。
2、希望能增加以下特性：
- 对弹幕行数的控制；
- 对弹幕字体、字号的控制；
- 对弹幕速度的控制。

### 建议解决方案

由于弹幕涉及的变量较多，都放到命令行里太冗长，可以考虑跟其他的变量和使用说明一起放到一个配置文件里，使用的时候直接：yutto /path/to/config/file
或者
docker run --rm -it -v /path/to/download:/app -v /path/to/config/file:/config siguremo/yutto  

### 额外信息

感谢作者的所做的工作～

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [X] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
关于弹幕的更多控制，已在 #353 支持，后续也会逐步完善

使用方式可参考文档中新增章节「弹幕设置参数」，比如

```bash
yutto ep828164 -c --danmaku-speed 3.6 --danmaku-opacity 0.9 --danmaku-font-size 50 --danmaku-display-region-ratio 0.3 --danmaku-block-keyword-patterns "垂死病中"
```

关于配置文件，则是另外一回事了，这个之后会考虑
