### ISSUE TITLE
✨ 批量下载封面

### ISSUE THREAD

**Issue by isleon** [yutto-dev/yutto#30]
### 特性描述

因为想导入到Jellyfin，有封面的话便于查看，是否有添加此功能的计划呢

**Comment by LockRim** [comment]
蛮需要这个功能的
下面可以提供一点思路
抓取的网页中有封面的url 在页面的 `itemprop="image“` 里面的 `content` 的值中
FFmpeg命令为：
```
ffmpeg -i [VIDEO] -i [IMAGE] -map 0 -map 1 -c copy -c:v:1 png -disposition:v:1 attached_pic [OUT_VIDEO]
```

**Comment by SigureMo** [comment]
@LockRim 已在 #243 进行了初步支持，可以麻烦进行部分功能测试嘛？

```bash
pipx install git+https://github.com/yutto-dev/yutto.git@feat/add-cover-support --force
```

通过如上命令即可安装该分支的 yutto～

**Comment by LockRim** [comment]
> @LockRim 已在 #243 进行了初步支持，可以麻烦进行部分功能测试嘛？
> 
> ```shell
> pipx install git+https://github.com/yutto-dev/yutto.git@feat/add-cover-support --force
> ```
> 
> 通过如上命令即可安装该分支的 yutto～

有下载封面和合并的行为
但我这里下载到的封面是视频开头的2帧左右的图片，不是封面图
还发现一点是使用 `--vcodec='hevc:copy'` ffmpeg合并会报错，其余格式没问题
[hevc_ffmpeg.txt](https://github.com/yutto-dev/yutto/files/14328289/hevc_ffmpeg.txt)

**Comment by SigureMo** [comment]
> > @LockRim 已在 #243 进行了初步支持，可以麻烦进行部分功能测试嘛？
> > 
> > ```shell
> > pipx install git+https://github.com/yutto-dev/yutto.git@feat/add-cover-support --force
> > ```
> > 
> > 通过如上命令即可安装该分支的 yutto～
> 
> 有下载封面和合并的行为
> 但我这里下载到的封面是视频开头的2帧左右的图片，不是封面图
> 还发现一点是使用 `--vcodec='hevc:copy'` ffmpeg合并会报错，其余格式没问题
> [hevc_ffmpeg.txt](https://github.com/yutto-dev/yutto/files/14328289/hevc_ffmpeg.txt)
> 
> 

可以麻烦提供下两个问题各自的复现命令嘛？我稍后测试下

**Comment by LockRim** [comment]
> 
> 可以麻烦提供下两个问题各自的复现命令嘛？我稍后测试下

```
yutto https://www.bilibili.com/video/BV1vt421p7Fz/
```
```
yutto --vcodec='hevc:copy' https://www.bilibili.com/video/BV1vt421p7Fz/
```

**Comment by SigureMo** [comment]
@LockRim 两个问题应该都修复了～可以麻烦重新测试一下嘛？

**Comment by LockRim** [comment]
> @LockRim 两个问题应该都修复了～可以麻烦重新测试一下嘛？

我这边测试没有问题
大佬辛苦了
