### ISSUE TITLE
🐛 PyPI 上 biliass 2.0.0a1 的 Cargo workspace 配置出错

### ISSUE THREAD

**Issue by ouuan** [yutto-dev/yutto#335]
### 问题简述

https://pypi.io/packages/source/b/biliass/biliass-2.0.0a1.tar.gz 中缺了一行 https://github.com/yutto-dev/yutto/blob/41b77c0bfa98c8d0c4cdc6f05b2ecf6f4b420f34/packages/biliass/Cargo.toml#L2C1-L2C20

### 复现方式

https://github.com/ouuan/AUR-packages/actions/runs/10987383463/job/30502134039

### 环境信息

N/A

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [X] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
发现 maturin build 之后就会删掉这个字段

不过这个 `Cargo.toml` 原来只是为了方便开发放在根目录用的，现在没啥用了，直接删掉了，不带这个 `Cargo.toml` 是可以正常进行 PEP 517 build 的

稍后修复并发一个新版本～感谢发现问题，不然之后 Homebrew 那边也会挂掉～

**Comment by SigureMo** [comment]
经验证，2.0.0-alpha.2 应该没这个问题了～

```bash
uvx --with https://files.pythonhosted.org/packages/5b/d5/7d86f0cad5df6925b9aaa9f2d931c5dd92089f6537e45c701c0f665d3c3a/biliass-2.0.0a2.tar.gz biliass
```
