### ISSUE TITLE
🐛 很多视频下载报错，发生概率很大：超出最大重试次数！

### ISSUE THREAD

**Issue by Dian-Kido** [yutto-dev/yutto#358]
### 问题简述

报错内容：
 投稿视频  纯黑《剑星(星刃)》迅猛无伤完虐BOSS攻略解说
 INFO  开始处理视频 纯黑《剑星(星刃)》迅猛无伤完虐BOSS攻略解说
 INFO  共包含以下 6 个视频流：
 INFO    0 [HEVC] [ 852x480 ] <480P 清晰 > #3
 INFO  * 1 [AVC ] [ 852x480 ] <480P 清晰 > #3
 INFO    2 [AV1 ] [ 852x480 ] <480P 清晰 > #3
 INFO    3 [HEVC] [ 640x360 ] <360P 流畅 > #3
 INFO    4 [AVC ] [ 640x360 ] <360P 流畅 > #3
 INFO    5 [AV1 ] [ 640x360 ] <360P 流畅 > #3
 INFO  共包含以下 3 个音频流：
 INFO  * 0 [MP4A] <320kbps >
 INFO    1 [MP4A] < 64kbps >
 INFO    2 [MP4A] <128kbps >
 弹幕  ASS 弹幕已生成
 WARN  抓取失败（ConnectError），正在重试，剩余 2 次
 WARN  抓取失败（ConnectError），正在重试，剩余 1 次
 WARN  抓取失败（ConnectError），正在重试，剩余 0 次
Traceback (most recent call last):
  File "/opt/venv/bin/yutto", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/__main__.py", line 57, in main
    run(args_list)
  File "/opt/venv/lib/python3.12/site-packages/yutto/utils/funcutils/as_sync.py", line 39, in sync_func
    return asyncio.run(async_func(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/__main__.py", line 169, in run
    current_download_state = await start_downloader(
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/processor/downloader.py", line 371, in start_downloader
    await download_video_and_audio(client, video, video_path, audio, audio_path, options)
  File "/opt/venv/lib/python3.12/site-packages/yutto/processor/downloader.py", line 124, in download_video_and_audio
    vsize = await Fetcher.get_size(client, video["url"])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/venv/lib/python3.12/site-packages/yutto/utils/fetcher.py", line 53, in connect_n_times
    raise MaxRetryError("超出最大重试次数！")
yutto.exceptions.MaxRetryError: 超出最大重试次数！

资源例如：（概率还挺大的）
BV14G1RYpErj
BV1dJ4m1L7rN

我尝试按照其他Issues的提到解决方案
1、 添加 verify=False
2、增加 重试时间 和 超时时间
3、增加 SESSDATA 入参
但是依然无效~

### 复现方式

单视频下载，例如：
BV14G1RYpErj
BV1dJ4m1L7rN

### 环境信息

-  OS: MacOS and Linux
-  Python: 3.10
-  yutto: 2024-10-08 的最新main分支代码，分别采用了 docker、源码安装两种模式 豆包同样的错误。

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
尝试 #271

**Comment by Dian-Kido** [comment]
> 尝试 [#271](https://github.com/yutto-dev/yutto/issues/271)

您好，我尝试了，依然无法下载。

我尝试了链接中提到的两种方式：
1、添加 参数  --banned-mirrors-pattern "mirrorali"
2、注释 代码块：       
        # "dm_img_list": "[]",
        # "dm_img_str": dm_img_str_cache,
        # "dm_cover_img_str": dm_cover_img_str_cache,
依然无法下载

**Comment by SigureMo** [comment]
试一下 #359 呢？

```bash
pipx install git+https://github.com/yutto-dev/yutto.git@fetch-video-and-audio-size-by-using-mirrors --force
```

该 PR 只是根据报错信息里挂在了 `Fetcher.get_size` 进行了调整，所以也只可能解决这里的报错，如果报错位置变了（一定要注意报错位置），那么是其他的问题，请贴出来新的报错

**Comment by Dian-Kido** [comment]
> 试一下 [#359](https://github.com/yutto-dev/yutto/pull/359) 呢？
> 
> pipx install git+https://github.com/yutto-dev/yutto.git@fetch-video-and-audio-size-by-using-mirrors --force
> 该 PR 只是根据报错信息里挂在了 `Fetcher.get_size` 进行了调整，所以也只可能解决这里的报错，如果报错位置变了（一定要注意报错位置），那么是其他的问题，请贴出来新的报错


亲测有效~ 谢谢大佬，泰裤辣

**Comment by SigureMo** [comment]
好的，我 merge 下
