### ISSUE TITLE
🐛 aur 安装依赖不完整

### ISSUE THREAD

**Issue by Discreater** [yutto-dev/yutto#361]
### 问题简述

1. 提示缺少 pydantic 依赖，随后手动安装pydantic。
2. 再次下载时，提示缺少xdg依赖。
    - xdg貌似改名成了xdg-base-dirs，archlinux官方库里的xdg实际上是pyxdg，aur里只剩改名后的xdg-base-dirs。没有人打包旧的xdg的话，大概是装不了的。

看到pyproject.toml里有计划升级xdg了，建议尽早升级xdg版本。

### 复现方式

```shell
> paru -Sy yutto
> yutto --audio-only https://www.bilibili.com/video/BV16X4y127hC/
...
ModuleNotFoundError: No module named 'pydantic'
> paru -Sy python-pydantic
> yutto --audio-only https://www.bilibili.com/video/BV16X4y127hC/
...
ModuleNotFoundError: No module named 'xdg'
```

### 环境信息

-  OS: Arch linux on WSL2
-  Python: 3.12.7
-  yutto: 2.0.0rc3-1
-  FFmpeg: n7.0.2

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
`xdg` 依赖已移除，新版本 `2.0.0-rc.4` 已经发布，辛苦 @ouuan 添加一下 `pydantic` 依赖～

**Comment by SigureMo** [comment]
https://github.com/ouuan/AUR-packages/commit/d2c5403b39f28215e11a8e50062ffb85b0b2dc38 应该已经修复
