### ISSUE TITLE
🐛 无法使用批量下载功能下载 视频合集

### ISSUE THREAD

**Issue by zzinx58** [yutto-dev/yutto#391]
### 问题简述

OS: MacOS 15.2
zsh: yutto -b https://space.bilibili.com/378394448/channel/collectiondetail?sid=1702028
zsh: no matches found: https://space.bilibili.com/378394448/channel/collectiondetail?sid=1702028
yutto Version: yutto 2.0.0-rc.5

### 复现方式

zsh: yutto -b https://space.bilibili.com/378394448/channel/collectiondetail?sid=1702028

### 环境信息

-  OS: 操作系统类型及其版本号
-  Python: Python 版本号 (`python --version`)
-  yutto: yutto 版本号 (`yutto -v`)
-  FFmpeg: FFmpeg 版本号 (`ffmpeg -version`)
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
这不是你 shell 用法的问题吗？用 zsh 的话需要用引号包裹 url

```bash
yutto -b 'https://space.bilibili.com/378394448/channel/collectiondetail?sid=1702028'
```

**Comment by zzinx58** [comment]
乌龙了, 感谢回复!!
