### ISSUE TITLE
✨ 免登录下载1080p？

### ISSUE THREAD

**Issue by oldherl** [yutto-dev/yutto#392]
### 特性描述

现在b站不登录只能观看 480p，本软件也是如此

### 建议解决方案

这个 userscript 可以做到免登录观看 1080p 画质，所以技术上应该是可行的？
https://greasyfork.org/zh-CN/scripts/467511-bilibili-在未登录的情况下自动并无限试用最高画质

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
> - [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式
