### ISSUE TITLE
✨ 增加繁中字幕翻译功能

### ISSUE THREAD

**Issue by zjns** [yutto-dev/yutto#40]
### 特性描述

主要是自己有下载港澳台地区番剧观看的需求，但B站只有较近的番剧有字幕且一般只有繁体，所以想着加一个自动翻译繁中字幕，并生成简中字幕的功能。

### 建议解决方案

我fork的分支已经基于[繁化姬](https://docs.zhconvert.org/)粗略的做了一版，但我觉得要做的话，可以完善翻译这个功能，比如说台湾朋友下载了B站仅带有简中CC字幕的视频，他想繁化。所以可以加一个类似`--sub_prefer_lang`的选项，比如是`zh-Hant`，就检查源本是是否有繁体CC字幕，如果没有，再检查是否有简体CC字幕，如果有，就调用三方API或者OpenCC翻译一份繁体字幕。

### 额外信息

其实我觉得字幕内嵌（烧录）的意义不大，不灵活，而且B站也只有CC字幕，没有带有样式的ASS字幕，但可以把字幕打包进视频，我fork的分支采用mkv容器，这样我可以把源本身的字幕和翻译的字幕一同打包进视频，并选定简体中文作为默认字幕。

另外调试的时候发现[downloader.py#178](https://github.com/SigureMo/yutto/blob/7cafb05312afbcb1f4c9b0e4589eea70aa285455/yutto/processor/downloader.py#L178)行有个小错误，audio写成了video。

**Comment by SigureMo** [comment]
关于字幕的翻译是有计划做的，不仅要字幕文本翻译，还有直接通过语音转文本来从那些没有字幕的视频中获取字幕并进行翻译，这部分我是想集成一个工具的，yutto 调用他这样。这部分我是想用深度学习来做，但在之前的探索过程中没有发现比较合适的预训练模型，所以暂且搁置了……

当然如果太麻烦的话也可以找些其他的替代方案……

> 另外调试的时候发现downloader.py#178行有个小错误，audio写成了video。

欢迎 PR 呀

**Comment by zjns** [comment]
> 关于字幕的翻译是有计划做的，不仅要字幕文本翻译，还有直接通过语音转文本来从那些没有字幕的视频中获取字幕并进行翻译，这部分我是想集成一个工具的，yutto 调用他这样。这部分我是想用深度学习来做，但在之前的探索过程中没有发现比较合适的预训练模型，所以暂且搁置了……
> 
大哥格局大呀，想的周到，期待
> 欢迎 PR 呀
>
一个小问题，没必要。你下次commit改了便是

**Comment by SigureMo** [comment]
> 大哥格局大呀，想的周到，期待

😂，目前感觉有点难，大概率这个坑是填不上了

**Comment by yuhanjin** [comment]
编程方面是纯小白，不过这种语音转字幕的工具github上已经有啦，就是autosub，https://github.com/BingLingGroup/autosub，虽然说效果不是很好。
说到这个生成字幕的工具，剪映是我用过的工具里面最厉害的，生成字幕又快又好，还能自动翻译生成双语字幕，可惜只能在他们软件里面用

**Comment by zjns** [comment]
> 编程方面是纯小白，不过这种语音转字幕的工具github上已经有啦，就是autosub，https://github.com/BingLingGroup/autosub 虽然说效果不是很好。 说到这个生成字幕的工具，剪映是我用过的工具里面最厉害的，生成字幕又快又好，还能自动翻译生成双语字幕，可惜只能在他们软件里面用

谢谢推荐，有机会试试剪映的。

**Comment by UxAzhangxiaohua** [comment]
现在只能手动在用这里的脚本转换成简体，凑合着能用，不然没新番看感觉大会员p用没有https://github.com/dongshuyan/BIG52GB

**Comment by zjns** [comment]
> 现在只能手动在用这里的脚本转换成简体，凑合着能用，不然没新番看感觉大会员p用没有https://github.com/dongshuyan/BIG52GB

B站港澳台配合油猴脚本解除区域限制，再配合脚本里我写的简化功能，还能勉强看番
