### ISSUE TITLE
🐛 音频时长超过视频

### ISSUE THREAD

**Issue by Discreater** [yutto-dev/yutto#407]
### 问题简述

测试视频：BV12s421N7ir

仅下载音频文件时，得到的音频文件时长大于实际视频时长

### 复现方式

```sh
yutto BV12s421N7ir
yutto BV12s421N7ir --audio-only
```
视频文件时长和网站上几乎一致（4分26秒）
但是仅下载音频文件时，得到的aac音频文件时长为6分31秒，多出的部分没有声音

### 环境信息

-  OS: mac arm 15.2
-  Python:
-  yutto: yutto 2.0.0-rc.6
-  FFmpeg: 7.1
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [x] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题
- [x] 确认所希望下载的资源是本人有权限获取的，yutto 不提供任何超出本人权限的资源下载方式

**Comment by SigureMo** [comment]
可以复现

输入音频是没有问题的，但是输出的 aac 会多一些空白音频（在我这里是 `00:12:06.95`）

搜索发现 aac 是有类似问题的，比如 mpv-player/mpv#11697

稍后尝试下修改默认音频后缀为 m4a 来解决
