### ISSUE TITLE
✨ 保存配置文件

### ISSUE THREAD

**Issue by OperatorRosmontis** [yutto-dev/yutto#65]
### 特性描述

将cookie等信息保存到一个配置文件里，就不用每次使用都要再获取一遍cookie了

### 建议解决方案

在当前用户的目录（类似于C:\Users\Administrator）下创建.yutto目录，在这个目录里创建yutto.data文件，保存cookie等信息，初次使用需要保存，后续就从yutto.data文件里读取cookie等信息使用，若信息失效，要求用户重新设置即可。

### 一点点的自我检查

- [x] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
目前我不太认为 yutto 需要一个配置文件，yutto 目前的可配置项还比较少，增加配置感觉只是徒增复杂度。目前我个人认为使用 alias 完全可以轻松完成常用命令的复用，关于这方面可参考[自定义命令别名](https://github.com/yutto-dev/yutto#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4%E5%88%AB%E5%90%8D)，当然如果 Windows 的话建议自行找下 alias 解决方案。

**Comment by BoxuanZng** [comment]
> 目前我不太认为 yutto 需要一个配置文件，yutto 目前的可配置项还比较少，增加配置感觉只是徒增复杂度。目前我个人认为使用 alias 完全可以轻松完成常用命令的复用，关于这方面可参考[自定义命令别名](https://github.com/yutto-dev/yutto#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%91%BD%E4%BB%A4%E5%88%AB%E5%90%8D)，当然如果 Windows 的话建议自行找下 alias 解决方案。

Windows 下的 alias 解决方案都是写死的，不能整参数
例如:设置 ytt 为 yutto --no-danmaku -c 'xxxx'
运行 ytt xxxxx 仍然会提示没有指定 url
(文中的 xxx 为cookie，xxxxx 为url)

**Comment by SigureMo** [comment]
https://superuser.com/a/1146561
