### ISSUE TITLE
🐛 WARN  未安装 uvloop，无法使用其加速协程

### ISSUE THREAD

**Issue by Cforcharming** [yutto-dev/yutto#69]
### 问题简述

下载时提示，未安装uvloop，无法使用加速协程

pip install uvloop: 
Requirement already satisfied: uvloop in /usr/local/lib/python3.9/site-packages (0.16.0)

pip --version:
22.0.4

### 复现方式

yutto -d /path -c "sdafghgdfsfgghg" -b ss3365

### 环境信息

-  OS: macOS 12.2.1
-  Python: 3.9.10 / 3.10.2
-  yutto: 2.0.0-beta.11
-  FFmpeg: 5.0
-  如果是显示相关问题
    -  Shell: zsh 5.8
    -  Terminal: iTerm2 3.4.15
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by Cforcharming** [comment]
发现原因在yutto文件头执行python为 
/usr/local/Cellar/yutto/2.0.0b11/libexec/bin/python3.10
而 pip 默认为python 3.9，切换python版本时出错
切换python版本时应该修改这行

详细

which -a pip:
pip: aliased to noglob pip
/usr/local/bin/pip

which -a pip3:
/usr/local/bin/pip3
/usr/bin/pip3

pip --version
pip 22.0.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)

pip3 --version
pip 22.0.2 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)

**Comment by SigureMo** [comment]
请问是通过什么方式安装的？homebrew 吗？暂时 homebrew 版本还没添加 uvloop 支持，而且貌似 homebrew 每个应用环境都是隔离的（基于 venv），因此（应该）无法通过 pip 来直接为该环境安装 uvloop。

不过对于下载来说，uvloop 其实应该用处不大，uvloop 还可能导致一些不稳定的情况，因此该 warning 直接忽略就好了，没有任何影响，之后我会考虑移除该 warning～

**Comment by Cforcharming** [comment]
是的homebrew
