### ISSUE TITLE
🐛 下载视频到末尾零点几Mib时出现零速度或负速度显示

### ISSUE THREAD

**Issue by BoxuanZng** [yutto-dev/yutto#72]
### 问题简述

下载视频（包括单独视频、番剧等）到末尾零点几Mib时出现零速度或负速度显示

### 复现方式

yutto --no-danmaku -c "***************" -b XXX
(XXX代表URL)

### 环境信息

-  OS: Windows 10.0.22000
-  Python: Python 3.10.2
-  yutto: yutto 2.0.0-beta.12
-  FFmpeg: ffmpeg version n5.0-4-g911d7f167c-20220209

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [x] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
这给的信息也太少了啊……无法复现啊……

**Comment by BoxuanZng** [comment]
> 这给的信息也太少了啊……无法复现啊……

但我就这么用的，就出现了问题，怎么办

**Comment by SigureMo** [comment]
> > 这给的信息也太少了啊……无法复现啊……
> 
> 但我就这么用的，就出现了问题，怎么办

「但我也这么用的，就没出现问题，怎么办」

说这种话没有任何意义，只会平白浪费交流的时机，既然我都那么问了，为什么不提供更多有意义的信息呢？

比如 **「该问题在 2.0.0-beta.11 没有，而在 2.0.0-beta.12 才出现」**，再或者 **「该现象对下载没有任何影响，只是在显示上可能出了问题」**，再或者 **「目前我所有下载的视频都有此现象，而且每次下载都会出现该问题，这里给出几个示例视频：BVXXXXXXX」**

这些都是对错误定位有作用的，即便我无法解决，我也会给出解决方案，但你一个「怎么办」属实给我整乐了，不给我信息，还反问我怎么办，我哪知道怎么办

没有更多信息就直接 close 了

**Comment by BoxuanZng** [comment]
目前我所有下载的视频都有此现象，而且每次下载都会出现该问题，这里给出几个示例视频：BV1ea41147mo、BV1ES4y1K7cU
该问题在 2.0.0-beta.11 没有，而在 2.0.0-beta.12 才出现

**Comment by SigureMo** [comment]
> 该问题在 2.0.0-beta.11 没有，而在 2.0.0-beta.12 才出现

这个确定吗，可以麻烦回退到 2.0.0-beta.11 再试一下吗

我已经复查了 <https://github.com/yutto-dev/yutto/compare/v2.0.0-beta.11...v2.0.0-beta.12>，并没有针对下载逻辑的任何调整

**Comment by BoxuanZng** [comment]
> > 该问题在 2.0.0-beta.11 没有，而在 2.0.0-beta.12 才出现
> 
> 这个确定吗，可以麻烦回退到 2.0.0-beta.11 再试一下吗
> 
> 我已经复查了 [v2.0.0-beta.11...v2.0.0-beta.12](https://github.com/yutto-dev/yutto/compare/v2.0.0-beta.11...v2.0.0-beta.12)，并没有针对下载逻辑的任何调整

确定了，OK

**Comment by SigureMo** [comment]
关于问题页面能截个图吗……

**Comment by BoxuanZng** [comment]
后续再进行排查时，问题就消失了，不知道为什么。
