### ISSUE TITLE
✨ 视频合并问题

### ISSUE THREAD

**Issue by Felix2yu** [yutto-dev/yutto#85]
### 特性描述

当前视频只能合并为mp4，希望能支持别的容器比如mov。
另外HEVC视频合并后，在macOS中无法显示封面图片，也不能使用「预览.app」查看，ffmpeg需要加上`-tag:v hvc1`标签才能更好兼容macOS。可[参见](https://aaron.cc/ffmpeg-hevc-apple-devices)

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
#109 将会解决这两个问题～～～

> 当前视频只能合并为mp4，希望能支持别的容器比如mov。

将会提供 `--output-format` 和 `--ouput-format-audio-only` 用于控制输出格式（分别为含视频流情况和不含视频流情况的格式）

> 另外HEVC视频合并后，在macOS中无法显示封面图片，也不能使用「预览.app」查看，ffmpeg需要加上`-tag:v hvc1`标签才能更好兼容macOS。可[参见](https://aaron.cc/ffmpeg-hevc-apple-devices)

感谢分享方法，已经当输出编码为 `"hevc"` 时，在 FFmpeg 合并处理参数加上 `-tag:v hvc1`～
