### ISSUE TITLE
✨ 是否可以添加仅下载弹幕功能？

### ISSUE THREAD

**Issue by Ninlives** [yutto-dev/yutto#87]
### 特性描述

由于部分番剧和谐、删减情况比较严重，有时只想下载弹幕文件配合其他来源的资源食用。

### 建议解决方案

提供一个`--danmaku-only`选项表示仅下载弹幕。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
已于 #105 支持～
