### ISSUE TITLE
🐛  --audio-only 参数的处理逻辑

### ISSUE THREAD

**Issue by hui-shao** [yutto-dev/yutto#93]
### 问题简述

在添加 `--audio-only` 参数后，仍提示 “ERROR 不下载视频无法生成 ASS 弹幕”

![2022-10-01_161334](https://user-images.githubusercontent.com/31568606/193400091-6d6bc10e-b3c3-4c7a-acbd-a6b1765e4435.png)

### 复现方式

例如：
```
 yutto https://www.bilibili.com/video/BV1xW41197cE?p=2 --audio-only
```

### 环境信息

-  OS: Win10 21H2
-  Python: Python 3.9.13
-  yutto: yutto 2.0.0-beta.15
-  FFmpeg: ffmpeg version N-104375-g77970abb71-20211017 Copyright (c) 2000-2021 the FFmpeg developers
built with gcc 10-win32 (GCC) 20210408

### 额外信息

应该是处理流程的问题吧，检查到含有 `--audio-only` 的选项就不要进行生成 ASS 弹幕的流程啦。

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
> 这一点从逻辑上也说得通呀~ 因为 --audio-only 本身就是说“只下载音频”，这样似乎视频和弹幕就不应包含在内啦。
>
> 当然啦，这个只是我在使用时，发现不是很符合日常认知的地方，所以来提个小建议。

这个问题的话，我不太希望在用户可以手动控制的情况下有太多隐式的行为，这个问题可能需要再考虑下……

> 顺带请教一下，如何使用 yutto 下载一个视频的 P2 ？就是上边这个链接：`https://www.bilibili.com/video/BV1xW41197cE?p=2`
> 看文档上好像是说，url 带有 “p=n” 的参数，就会下载第 n P。但上边这个似乎不行。（或者是我理解错了，请指点）

是下载完 P1 后再下载 P2 嘛？一次只下载 1P 的话每次都会使用整个视频的标题作为视频名，所以两次使用了同一个视频名，会认为是同一个视频了，当然你可以通过修改默认的视频子路径模板来修改这一行为

不过要同时下载两话更推荐的方式是添加 `-b` 参数一次性下载

```bash
yutto -b 'https://www.bilibili.com/video/BV1xW41197cE/'
```

**Comment by hui-shao** [comment]
> 这个问题的话，我不太希望在用户可以手动控制的情况下有太多隐式的行为，这个问题可能需要再考虑下……

确实，你说的这个也很有道理哈哈，我没考虑到这个。可能可以加个提示之类的？

> 是下载完 P1 后再下载 P2 嘛？一次只下载 1P 的话每次都会使用整个视频的标题作为视频文件名，所以两次使用了同一个文件路径，会认为是同一个视频了，当然你可以通过修改默认的视频子路径模板来修改这一行为

> 不过要同时下载两话更推荐的方式是添加 -b 参数一次性下载

我是想单独下载 2P ，问题已经解决，添加 `-b -p 2` 就行啦。（因为是下载单P，就没想着往批量方面考虑，后来发现批量模式才支持指定P)，谢谢解答。
