### ISSUE TITLE
🐛最近是不是cookies过期了，还是怎么回事，只能下载到480P的视频 

### ISSUE THREAD

**Issue by rhaego989** [yutto-dev/yutto#97]
### 问题简述

最近是不是cookies过期了，还是怎么回事，只能下载到480P的视频，期待大佬回复

### 复现方式

/

### 环境信息

-  OS: windows10 1909
-  Python: Python 3.11.0
-  yutto: v2.0.0-beta.17
-  FFmpeg: ffmpeg version N-108766-geb9153b4a7-20221020
-  如果是显示相关问题
    -  Shell: Shell 类型 (`echo $SHELL`)
    -  Terminal: 终端类型
-  Others: 其它信息

### 一点点的自我检查

- [X] 充分阅读 [README.md](https://github.com/yutto-dev/yutto)，特别是与本 issue 相关的部分
- [X] 如果是网络问题，已经检查网络连接、设置是否正常，并经过充分测试认为这是 yutto 本身的问题
- [X] 本 issue 在 [issues](https://github.com/yutto-dev/yutto/issues) 和 [discussion](https://github.com/yutto-dev/yutto/discussions) 中并没有重复问题

**Comment by SigureMo** [comment]
唔，给个示例吧……以及运行的输出

> 最近是不是cookies过期了

如果是 cookies 过期的话，可以重新从浏览器找一下～

**Comment by rhaego989** [comment]
> 唔，给个示例吧……以及运行的输出
> 
> > 最近是不是cookies过期了
> 
> 如果是 cookies 过期的话，可以重新从浏览器找一下～

1. 这是没加sessdata时
[https://raw.githubusercontent.com/rhaego989/Issues/main/image_2022-11-09_22-32-01.png](url)

2. 这是加了sessdata时
[https://raw.githubusercontent.com/rhaego989/Issues/main/image_2022-11-09_22-38-28.png](url)

加了sessdata就可惜解析出更高的分辨率
只是每次下载都要添加sessdata，不过也是能用的，就是好奇原来那么久也没事，最近突然要填加sessdata了

**Comment by SigureMo** [comment]
> 加了sessdata就可惜解析出更高的分辨率
> 只是每次下载都要添加sessdata，不过也是能用的，就是好奇原来那么久也没事，最近突然要填加sessdata了

唔，这个我也不清楚，因为最近没有在积极维护所以也没有注意这些，估计就是 B 站对无 cookie 的进行了限制吧

另外 yutto 内置是没有 cookie 的，cookie 就是通过用户传入的 SESSDATA 构造的，所以不存在 yutto 内部 cookie 过期的问题

**Comment by rhaego989** [comment]
> > 加了sessdata就可惜解析出更高的分辨率
> > 只是每次下载都要添加sessdata，不过也是能用的，就是好奇原来那么久也没事，最近突然要填加sessdata了
> 
> 唔，这个我也不清楚，因为最近没有在积极维护所以也没有注意这些，估计就是 B 站对无 cookie 的进行了限制吧
> 
> 另外 yutto 内置是没有 cookie 的，cookie 就是通过用户传入的 SESSDATA 构造的，所以不存在 yutto 内部 cookie 过期的问题

明白，感谢！

**Comment by SigureMo** [comment]
> 明白，感谢！

嗯嗯，那我先 close 啦～
